name: Build Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Backend - Docker Compose
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker setup
        run: |
          docker --version
          docker compose version

      - name: Build Docker image
        working-directory: ./backend
        run: |
          echo "Building Docker image..."
          docker compose build

      - name: Run backend tests
        working-directory: ./backend
        run: |
          echo "Starting services..."
          docker compose up -d mongodb redis rabbitmq
          echo "Waiting for RabbitMQ to be ready..."
          until docker compose exec rabbitmq rabbitmq-diagnostics check_running > /dev/null 2>&1; do
            echo "RabbitMQ not ready yet..."
            sleep 3
          done
          echo "RabbitMQ is up, running backend tests..."
          docker compose run --rm backend ./gradlew build
