name: Build Front
on:
  workflow_call:

jobs:
  build:
      name: Build Front
      runs-on: ubuntu-latest
      timeout-minutes: 90
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Build Front
          run: |
            cd web
            npm install
            npm run build
