name: Mirror after all builds
on:
  workflow_run:
    workflows: ["Build Front"]
    types: [completed]

jobs:
  mirror:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Mirror to Area Epitech Repo
        run: |
          git remote add mirror git@github.com:EpitechPGE3-2025/G-DEV-500-PAR-5-1-area-18.git
          git push --mirror mirror --no-verify
